#!/usr/bin/env python3
"""
make_dashboard.py — generate a self-contained local HTML dashboard of the ranked
universe into exports/dashboard.html (founder-requested, 2026-06-12).

Deliberately NOT a web app: no server, no deploy, no new dependency. One static
file, regenerated by `make dashboard` (and at the end of `make refresh`), data
inlined as JSON. exports/ is gitignored — owner names, mailing addresses and
distress evidence stay on this machine. The Airtable board (Day 8) remains the
real working surface; this is a read-only viewer.

    python tools/make_dashboard.py [--out exports/dashboard.html]

The DB is hit only by collect(). Pass --from-json to rebuild the HTML from a saved
data snapshot with no Postgres at all (e.g. on a teammate's laptop), and --dump-json
to write that snapshot while you have the DB up. The DB import is lazy so --from-json
works even where lib.db can't connect.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime
from decimal import Decimal
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from tools.ranking import (  # noqa: E402  (pure — per-market ceiling + rank, shared with make_map)
    comp_max, fit_sort_key, live_components, market_ceiling)

ROWS_SQL = """
WITH latest AS (
  SELECT DISTINCT ON (apn) apn, total, components
  FROM scores WHERE version LIKE %(ver)s ORDER BY apn, scored_at DESC
),
owner AS (
  SELECT DISTINCT ON (o.apn) o.apn, e.entity_id, e.entity_type, e.is_out_of_state,
         e.name_raw, e.mailing_address
  FROM ownerships o JOIN entities e USING (entity_id) ORDER BY o.apn, e.entity_id
),
-- Best contact per entity: highest confidence, then most phones/emails. Joined per
-- market schema; entity_id is unique only within a market, hence the per-schema search_path.
contact AS (
  SELECT DISTINCT ON (entity_id) entity_id, person_name, role, phones, emails, confidence
  FROM contacts
  ORDER BY entity_id,
           CASE confidence WHEN 'high' THEN 3 WHEN 'medium' THEN 2 WHEN 'low' THEN 1 ELSE 0 END DESC,
           coalesce(array_length(phones, 1), 0) DESC,
           coalesce(array_length(emails, 1), 0) DESC
)
SELECT p.apn, p.situs_address, p.in_universe, p.manual_review, p.gate_reason,
       p.land_use_desc,
       pr.building_sf, pr.building_sf_largest, pr.building_count, pr.year_built,
       pr.clear_height_est, pr.clear_height_source,
       pr.distance_miles_icbd, pr.hold_years, pr.assessed_value,
       pr.last_sale_date, pr.last_sale_price, pr.sf_confidence,
       ow.entity_type, ow.is_out_of_state, ow.name_raw, ow.mailing_address,
       c.person_name AS contact_person, c.role AS contact_role,
       c.phones AS contact_phones, c.emails AS contact_emails,
       c.confidence AS contact_confidence,
       l.total, l.components
FROM parcels p
JOIN properties pr USING (apn)
LEFT JOIN owner ow ON ow.apn = p.apn
LEFT JOIN contact c ON c.entity_id = ow.entity_id
LEFT JOIN latest l ON l.apn = p.apn
WHERE p.in_universe OR p.manual_review
"""

SIGNALS_SQL = """
SELECT apn, type, detail, event_date
FROM distress_signals
ORDER BY apn, event_date DESC NULLS LAST
"""

# Imagery/VLM pass per parcel (the Chrome-extension human-VLM or, later, the API VLM).
# lat/lon (point-on-surface) lets us rebuild the source satellite link client-side.
OBS_SQL = """
SELECT so.apn, so.parking_fullness, so.signage_present, so.condition, so.divisibility,
       so.truck_access, so.dock_doors_est, so.drive_ins_est,
       so.vlm_json, so.captured_at, so.model_version,
       ST_Y(ST_PointOnSurface(p.geom)) AS lat, ST_X(ST_PointOnSurface(p.geom)) AS lon
FROM site_observations so JOIN parcels p USING (apn)
"""


def _js(o):
    if isinstance(o, Decimal):
        return float(o)
    if isinstance(o, (date, datetime)):
        return o.isoformat()
    raise TypeError(type(o))


def _comp_max() -> dict:
    """Per-component point ceiling (delegates to tools.ranking so dashboard + map share it)."""
    return comp_max()


def _label(name: str) -> str:
    """'columbus' -> 'Columbus' (display + City column / filter value)."""
    return name[:1].upper() + name[1:]


def _place(name: str) -> str:
    """'City, ST' suffix for the Google Maps link (state from the market home_state)."""
    from lib.market import home_state
    st = home_state(name)
    return f"{_label(name)}, {st}" if st else _label(name)


def _obs_dict(o: dict) -> dict:
    """One site_observations row -> the dashboard's compact imagery-assessment dict.
    Mirrors outreach/call_sheets.py:site_assessment_lines (parity of what a reviewer sees)."""
    vlm = o["vlm_json"] or {}
    use = vlm.get("use_truth") or {}
    ten = vlm.get("tenant") or {}
    lat, lon = o.get("lat"), o.get("lon")
    src = (f"https://www.google.com/maps/@{lat},{lon},19z/data=!3m1!1e3"
           if lat is not None else None)
    return {
        "park": o["parking_fullness"], "sign": o["signage_present"], "cond": o["condition"],
        "div": o["divisibility"], "truck": o["truck_access"],
        "docks": o["dock_doors_est"], "drive": o["drive_ins_est"],
        "use": use.get("actual_use"), "match": use.get("matches_landuse"),
        "ten": ten.get("operating_business") or [],
        "tency": ten.get("tenancy"), "occ": ten.get("occupancy"),
        "ctx": vlm.get("context"), "note": vlm.get("note"),
        "src": src, "cap": o["captured_at"].isoformat() if o["captured_at"] else None,
        "ver": o["model_version"],
    }


def _shape_rows(rows: list, sig_rows: list, obs_rows: list, label: str, place: str) -> list:
    """Turn raw query rows for ONE market into the dashboard's compact row dicts,
    tagged with the market's city + map place."""
    signals: dict[str, list] = {}
    for s in sig_rows:
        signals.setdefault(s["apn"], []).append(
            {"type": s["type"], "detail": (s["detail"] or "")[:220],
             "date": s["event_date"].isoformat() if s["event_date"] else None})
    obs = {o["apn"]: _obs_dict(o) for o in obs_rows}

    # Bulk/portfolio-sale detector: county CAMA stamps the whole deal's consideration on every
    # parcel in a multi-parcel sale, so a per-SF price off that figure is nonsense. Parcels sharing
    # the exact same sale date AND price are one deal — count them so the detail can flag it.
    from collections import Counter
    deal = Counter((r["last_sale_date"], float(r["last_sale_price"] or 0))
                   for r in rows if (r["last_sale_price"] or 0) > 0)

    out = []
    for r in rows:
        comp = (r["components"] or {}).get("components", {})
        out.append({
            "city": label,
            "place": place,
            "apn": r["apn"],
            "addr": r["situs_address"] or "(no address)",
            "bucket": "universe" if r["in_universe"] else "manual review",
            "gate": r["gate_reason"],
            "lu": r["land_use_desc"],
            "score": float(r["total"]) if r["total"] is not None else None,
            "comp": {k: float(v) for k, v in comp.items()},
            "sf": float(r["building_sf"] or 0),
            "sfL": float(r["building_sf_largest"] or 0),
            "nb": r["building_count"],
            "yr": r["year_built"],
            "ch": float(r["clear_height_est"]) if r["clear_height_est"] is not None else None,
            "chs": r["clear_height_source"],
            "mi": float(r["distance_miles_icbd"] or 0),
            "hold": float(r["hold_years"] or 0),
            "av": float(r["assessed_value"] or 0),
            "sale": r["last_sale_date"].isoformat() if r["last_sale_date"] else None,
            "price": float(r["last_sale_price"] or 0),
            "pn": deal.get((r["last_sale_date"], float(r["last_sale_price"] or 0)), 1),
            "sfc": r["sf_confidence"],
            "ot": r["entity_type"] or "?",
            "oos": bool(r["is_out_of_state"]),
            "own": r["name_raw"] or "?",
            "mail": r["mailing_address"] or "",
            # Owner contact (from public-records research, loaded into `contacts`).
            "person": r.get("contact_person") or "",
            "prole": r.get("contact_role") or "",
            "phones": list(r.get("contact_phones") or []),
            "emails": list(r.get("contact_emails") or []),
            "cc": r.get("contact_confidence") or "",
            "sig": signals.get(r["apn"], []),
            "obs": obs.get(r["apn"]),
        })
    return out


def collect(markets: list | None = None) -> dict:
    """Pull EVERY built market's universe into one dataset, each row tagged with its
    city — a single file with all cities in one table, not a file per market.

    Markets are the markets/<name>.yaml files (default: all of them). A market whose
    schema has no parcels table, or no universe rows yet (e.g. Columbus before its first
    run), is silently skipped — so the same command yields a one-city file today and a
    multi-city file the moment another market lands. Each market is read on its own
    connection with its schema on the search_path, so two markets never collide."""
    from lib.db import cursor
    from lib.market import db_schema, MARKETS_DIR
    if not markets:
        markets = sorted(p.stem for p in MARKETS_DIR.glob("*.yaml"))

    all_rows: list = []
    per_market: list = []
    cmax = comp_max()
    city_ceil: dict = {}
    city_live: dict = {}
    for name in markets:
        schema = db_schema(name)
        try:
            with cursor(dict_rows=True, commit=False) as cur:
                cur.execute("SELECT to_regclass(%s) AS reg", (f"{schema}.parcels",))
                if cur.fetchone()["reg"] is None:
                    continue  # schema not created yet
                cur.execute(f'SET search_path TO "{schema}", public')
                cur.execute(ROWS_SQL, {"ver": "%-final"})
                rows = [dict(r) for r in cur.fetchall()]
                if not rows:
                    continue  # configured but not built (no universe rows)
                cur.execute(SIGNALS_SQL)
                sig_rows = cur.fetchall()
                cur.execute(OBS_SQL)
                obs_rows = cur.fetchall()
        except Exception as e:  # a half-migrated market must not sink the whole file
            print(f"  ! skipped market '{name}': {e}", file=sys.stderr)
            continue
        shaped = _shape_rows(rows, sig_rows, obs_rows, _label(name), _place(name))
        # A1: judge each market against ONLY the points its own feeds can earn.
        ceil = market_ceiling(shaped, cmax)
        for x in shaped:
            x["ceil"] = ceil
        all_rows.extend(shaped)
        per_market.append({
            "city": _label(name),
            "n_universe": sum(1 for x in shaped if x["bucket"] == "universe"),
            "n_manual": sum(1 for x in shaped if x["bucket"] == "manual review"),
            "ceil": ceil,
        })
        city_ceil[_label(name)] = ceil
        city_live[_label(name)] = live_components(shaped, cmax)

    # Rank the unified leaderboard by the BLENDED fit-and-evidence metric (tools.ranking
    # fit_sort_key = score/sqrt(ceiling)), not raw score: rewards both % fit and absolute
    # evidence, so a feed-poor market is neither buried nor floods the top (HEALTH_AUDIT §A1).
    all_rows.sort(key=fit_sort_key)
    return {"generated": datetime.now().strftime("%Y-%m-%d %H:%M"),
            "n_universe": sum(1 for x in all_rows if x["bucket"] == "universe"),
            "n_manual": sum(1 for x in all_rows if x["bucket"] == "manual review"),
            "markets": per_market,
            "comp_max": cmax,
            "city_ceil": city_ceil,
            "city_live": city_live,
            "rows": all_rows}


TEMPLATE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Nashville sourcing — ranked universe</title>
<style>
:root{--ink:#1a1a18;--mut:#6b6a64;--line:#e4e2da;--bg:#faf9f5;--card:#fff;
--teal:#0f6e56;--tealbg:#e1f5ee;--amber:#854f0b;--amberbg:#faeeda;--red:#a32d2d;--redbg:#fcebeb}
*{box-sizing:border-box}body{margin:0;font:14px/1.55 -apple-system,'Segoe UI',sans-serif;color:var(--ink);background:var(--bg)}
.wrap{max-width:1180px;margin:0 auto;padding:24px 20px 80px}
h1{font-size:20px;font-weight:600;margin:0 0 2px}
.sub{color:var(--mut);font-size:12.5px;margin-bottom:18px}
.warn{display:inline-block;background:var(--amberbg);color:var(--amber);border-radius:6px;padding:2px 8px;font-size:11.5px;margin-left:8px}
.stats{display:flex;gap:26px;flex-wrap:wrap;margin:0 0 16px;font-size:13px;color:var(--mut)}
.stats b{display:block;font-size:19px;font-weight:600;color:var(--ink)}
.bar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:14px;align-items:center}
input[type=search]{padding:7px 11px;border:1px solid var(--line);border-radius:8px;font-size:13px;width:240px;background:var(--card)}
select{padding:7px 9px;border:1px solid var(--line);border-radius:8px;font-size:13px;background:var(--card)}
label.cb{font-size:12.5px;color:var(--mut);display:flex;align-items:center;gap:5px}
table{width:100%;border-collapse:collapse;background:var(--card);border:1px solid var(--line);border-radius:10px;overflow:hidden}
th{font-size:11.5px;text-transform:uppercase;letter-spacing:.04em;color:var(--mut);text-align:left;padding:9px 10px;border-bottom:1px solid var(--line);cursor:pointer;user-select:none;white-space:nowrap;background:#f4f3ee}
th.r,td.r{text-align:right}
td{padding:9px 10px;border-bottom:1px solid var(--line);vertical-align:top}
tr.main{cursor:pointer}tr.main:hover{background:#f6f5f0}
.addr{font-weight:600}.apn{font-size:11px;color:var(--mut)}
.chip{display:inline-block;border-radius:9px;padding:0 7px;font-size:11px;background:#efeee8;color:var(--mut);margin-right:4px}
.chip.hot{background:var(--tealbg);color:var(--teal)}
.chip.warnc{background:var(--amberbg);color:var(--amber)}
.chip.redc{background:var(--redbg);color:var(--red)}
.chip.soft{background:#f0efe9;color:#908e84}
.chip.none{background:transparent;color:#b9b7ae;padding:0}
.cperson{font-size:12px;font-weight:600;max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.cph{font-size:12px;color:var(--teal);font-variant-numeric:tabular-nums}
.cem{font-size:11px;color:var(--teal);max-width:150px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
.facts dd a{color:var(--teal);text-decoration:none}.facts dd a:hover{text-decoration:underline}
.scwrap{display:flex;flex-direction:column;gap:5px;align-items:flex-start}
.scorepill{min-width:30px;text-align:center;font-weight:700;font-size:13px;line-height:1.5;padding:1px 8px;border-radius:7px;font-variant-numeric:tabular-nums}
.scorepill.hi{background:var(--tealbg);color:var(--teal)}
.scorepill.mid{background:var(--amberbg);color:var(--amber)}
.scorepill.lo{background:#edebe4;color:#6b6a64}
.scorepill.na{background:transparent;color:var(--mut);font-weight:400;padding-left:0}
.fitpct{font-size:10px;color:var(--mut);font-variant-numeric:tabular-nums}
.sbar{width:78px;height:5px;border-radius:3px;background:#eceae3;overflow:hidden}
.sbar i{display:block;height:100%;border-radius:3px;background:#cdcabf}
.sbar.hi i{background:#1d9e75}.sbar.mid i{background:#d98a2b}.sbar.lo i{background:#b7b4a8}
tr.det td{background:#fbfaf7;font-size:12.5px}
.bkhd{font-size:12px;color:var(--mut);margin:2px 0 9px}.bkhd b{color:var(--ink);font-size:14px;font-weight:700}
.cbreak{display:grid;grid-template-columns:128px 1fr 52px;gap:6px 12px;align-items:center;max-width:520px;margin:0 0 10px}
.cbreak .lab{font-size:12px;color:var(--ink)}
.cbreak .track{height:8px;border-radius:4px;background:#ece9e1;overflow:hidden}
.cbreak .fill{display:block;height:100%;border-radius:4px;background:#1d9e75}
.cbreak .fill.z{width:0}
.cbreak .val{font-size:12px;color:var(--mut);text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}
.cbreak .val b{color:var(--ink);font-weight:600}
.pendrow{font-size:11.5px;color:#9a988f;margin:-2px 0 10px;max-width:560px;line-height:1.55}
.pendrow b{color:#6b6a64;font-weight:600}
.cgrid{display:flex;flex-wrap:wrap;gap:4px 18px;margin:4px 0 8px}
.cgrid span{white-space:nowrap;color:var(--mut)}.cgrid b{color:var(--ink);font-weight:600}
.muted{color:var(--mut)}
.facts{display:grid;grid-template-columns:auto 1fr;gap:4px 16px;max-width:680px;margin:2px 0 13px;align-items:baseline}
.facts dt{color:var(--mut);font-size:11px;text-transform:uppercase;letter-spacing:.03em;white-space:nowrap}
.facts dd{margin:0;color:var(--ink);font-size:12.5px}
.evhd{font-size:11px;text-transform:uppercase;letter-spacing:.03em;color:var(--mut);margin:0 0 7px}
.evlist{display:flex;flex-direction:column;gap:7px;max-width:780px;margin:0 0 13px}
.evrow{display:flex;gap:9px;align-items:flex-start}
.evrow .tag{flex:none;font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.04em;padding:2px 7px;border-radius:5px;margin-top:1px;min-width:62px;text-align:center}
.evrow .tag.v{background:var(--redbg);color:var(--red)}
.evrow .tag.p{background:#f0efe9;color:#8a887f}
.evrow .ev{font-size:12.5px;color:var(--ink);line-height:1.5}
.evrow .ev .when{color:var(--mut);font-variant-numeric:tabular-nums;margin-right:6px}
.mapbtn{display:inline-flex;align-items:center;gap:5px;padding:6px 12px;border:1px solid var(--line);border-radius:8px;background:var(--card);color:var(--teal);font-size:12.5px;font-weight:600;text-decoration:none}
.mapbtn:hover{background:#f1f7f4;border-color:#bfe0d4}
.foot{margin-top:14px;font-size:12px;color:var(--mut)}
.rvb{background:#fffdf6;border:1px solid #ecdfb4;border-radius:10px;padding:13px 15px;margin-bottom:14px;font-size:13px;line-height:1.5}
.rvb h3{margin:0 0 4px;font-size:14px;font-weight:600}
.rvb ol{margin:6px 0 0;padding-left:20px}.rvb li{margin-bottom:2px}
.exbar{position:sticky;top:0;z-index:9;background:var(--bg);border-bottom:1px solid var(--line);padding:10px 0;margin-bottom:6px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.exbar input{padding:7px 10px;border:1px solid var(--line);border-radius:8px;font-size:13px;background:var(--card)}
.btn{padding:7px 13px;border:1px solid var(--line);border-radius:8px;background:var(--card);font-size:13px;cursor:pointer;color:var(--ink)}
.btn.primary{background:var(--teal);color:#fff;border-color:var(--teal);font-weight:600}
.cnt{font-size:12.5px;color:var(--mut)}
.vdot{font-size:13px;margin-right:3px}
.vbtns{display:flex;gap:7px;margin:8px 0 4px}
.vb{padding:5px 12px;border:1px solid var(--line);border-radius:15px;background:var(--card);cursor:pointer;font-size:12.5px;color:var(--mut)}
.vb.on.good{background:var(--tealbg);border-color:var(--teal);color:var(--teal);font-weight:600}
.vb.on.bad{background:var(--redbg);border-color:var(--red);color:var(--red);font-weight:600}
.vb.on.maybe{background:var(--amberbg);border-color:var(--amber);color:var(--amber);font-weight:600}
.rnote{display:block;width:100%;max-width:560px;min-height:48px;border:1px solid var(--line);border-radius:8px;padding:8px;font:13px -apple-system,'Segoe UI',sans-serif;margin-top:2px;resize:vertical}
</style></head><body><div class="wrap">
<h1><span id="htitle">Off-market industrial — ranked universe</span> <span class="warn">internal · do not publish</span></h1>
<div class="sub">Generated __GEN__ · local file, no server · the Airtable board is the working surface — this is a read-only viewer</div>
__REVIEW__
<div class="stats" id="stats"></div>
<div class="bar">
  <input type="search" id="q" placeholder="Search address / owner / APN">
  <select id="city"><option value="">All cities</option></select>
  <select id="otype"><option value="">All owner types</option></select>
  <select id="minsf"><option value="0">Any size</option><option value="60000">≥ 60k SF</option>
    <option value="75000">≥ 75k SF</option><option value="100000">≥ 100k SF</option>
    <option value="125000">≥ 125k SF</option><option value="150000">≥ 150k SF</option>
    <option value="200000">≥ 200k SF</option><option value="250000">≥ 250k SF</option>
    <option value="300000">≥ 300k SF</option><option value="500000">≥ 500k SF</option>
    <option value="1000000">≥ 1M SF</option></select>
  <select id="maxsf"><option value="0">No max</option><option value="100000">≤ 100k SF</option>
    <option value="150000">≤ 150k SF</option><option value="200000">≤ 200k SF</option>
    <option value="300000">≤ 300k SF</option><option value="500000">≤ 500k SF</option></select>
  <select id="minscore"><option value="">Any score</option><option value="mid">Moderate +</option>
    <option value="hi">Strong only</option></select>
  <select id="maxch" autocomplete="off"><option value="0">Any clear height</option><option value="16">≤ 16 ft clear</option>
    <option value="20">≤ 20 ft clear</option><option value="24">≤ 24 ft clear</option>
    <option value="28">≤ 28 ft clear</option><option value="32">≤ 32 ft clear</option></select>
  <select id="maxmi"><option value="0">Any distance</option><option value="5">≤ 5 mi to core</option>
    <option value="10">≤ 10 mi</option><option value="15">≤ 15 mi</option></select>
  <select id="minhold"><option value="0">Any hold</option><option value="5">held ≥ 5 yr</option>
    <option value="10">held ≥ 10 yr</option><option value="20">held ≥ 20 yr</option></select>
  <select id="ownerloc"><option value="">Any owner location</option>
    <option value="in">In-state owner</option><option value="out">Out-of-state owner</option></select>
  <label class="cb"><input type="checkbox" id="mr"> include 60–75k manual review</label>
  <label class="cb"><input type="checkbox" id="sigonly"> has distress signals</label>
  <a class="mapbtn" href="map.html" target="_top" style="margin-left:auto" title="See every property plotted on a map">🗺 Map view ↗</a>
</div>
<table><thead><tr>
<th data-k="rank" title="Rank by fit score">#</th>
<th data-k="addr" title="Address, APN and owner type">Property / owner</th>
<th data-k="city" title="Market / city">City</th>
<th class="r" data-k="sf" title="Total building area — sum of all buildings on the parcel">SF</th>
<th class="r" data-k="nb" title="Number of buildings on the parcel">Bldgs</th>
<th class="r" data-k="yr" title="Year built — older is a clear-height / obsolescence proxy">Built</th>
<th class="r" data-k="ch" title="Roof/eave height from free 2022 aerial LiDAR — an estimate of clear height (interior clear is ~2-4 ft less). Confirm on call.">Clr (ft)</th>
<th class="r" data-k="mi" title="Miles to the industrial core (5th &amp; Broadway)">Dist (mi)</th>
<th class="r" data-k="hold" title="Years the current owner has held the property">Held (yr)</th>
<th data-k="score" title="Fit score (raw points) + % fit = score ÷ the points reachable in THAT market. Rank (#) blends % fit with raw evidence so feed-poor markets are neither buried nor over-promoted.">Score</th>
<th title="Distress signals — code violations (strong) and permit anomalies (weak)">Signals</th>
<th title="Owner contact — person + phone/email from public-records research">Contact</th>
</tr></thead><tbody id="tb"></tbody></table>
<div class="foot">Click any row for the score breakdown, distress evidence and a map link.
Score color: <span class="scorepill hi">strong</span> <span class="scorepill mid">moderate</span>
<span class="scorepill lo">lower</span> — each market is judged against the points <i>its</i> data can reach
(shown per row), so data-poor markets aren't penalised; the rest stay locked until imagery + tax data land.</div>
</div>
<script>
const DATA=__DATA__;
const REVIEW=__REVIEW_FLAG__;
const rows=DATA.rows.map((r,i)=>({...r,rank:r.score==null?9999:i+1}));
const tb=document.getElementById('tb');
const CMAX=DATA.comp_max||{};
const CLABEL={proximity_score:'Proximity to core',vacancy_evidence:'Vacancy evidence',
tax_delinquency:'Tax delinquency',physical_fit:'Physical fit',code_violations:'Code violations',
hold_period:'Hold period',owner_profile:'Owner profile',permit_anomaly:'Permit anomaly',
year_built_band:'Year-built band',truck_access_inverse:'Truck access'};
// A component is "live" once any scored row earns points from it. The dormant ones
// (vacancy, physical fit, tax, truck access) are pending data — they're why the reachable
// ceiling sits below 100, so the score bar/colour are judged against that live ceiling.
const CKEYS=Object.keys(CMAX);
// A1 (per-market reachable ceiling): judge each parcel against ONLY the points its own
// market's feeds can earn. city_ceil/city_live come from the server (tools/ranking.py);
// fall back to a global ceiling for old --from-json snapshots that predate them.
const CITY_CEIL=DATA.city_ceil||{},CITY_LIVE=DATA.city_live||{};
const GLOBAL_LIVE={};rows.forEach(r=>{const c=r.comp||{};for(const k in c)if(c[k]>0)GLOBAL_LIVE[k]=1;});
const GLOBAL_CEIL=CKEYS.reduce((s,k)=>s+(GLOBAL_LIVE[k]?CMAX[k]:0),0)||100;
function ceilFor(r){return (r&&r.ceil)||(r&&CITY_CEIL[r.city])||GLOBAL_CEIL;}
function liveFor(r){return (r&&CITY_LIVE[r.city])||CKEYS.filter(k=>GLOBAL_LIVE[k]);}
function tier(r){if(r==null||r.score==null)return 'na';const p=r.score/ceilFor(r);return p>=0.66?'hi':p>=0.4?'mid':'lo';}
const VICON={fit:'<span class="vdot" style="color:var(--teal)">●</span>',
maybe:'<span class="vdot" style="color:var(--amber)">●</span>',
no:'<span class="vdot" style="color:var(--red)">●</span>'};
const VK='nsg_fb_'+DATA.generated;
// localStorage throws SecurityError on file:// in Safari / locked-down Chrome /
// sandboxed email+Drive previews. Keep it non-fatal so the table still renders
// when this file is opened as a shared attachment — feedback just won't persist.
const store={get(k){try{return localStorage.getItem(k);}catch(e){return null;}},
set(k,v){try{localStorage.setItem(k,v);}catch(e){}}};
let FB={};try{FB=REVIEW?JSON.parse(store.get(VK)||'{}'):{};}catch(e){FB={};}
function saveFB(){store.set(VK,JSON.stringify(FB));updCount();}
function esc(s){return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}
function setVerdict(apn,v){FB[apn]=FB[apn]||{};FB[apn].v=(FB[apn].v===v?'':v);saveFB();render();}
function setNote(apn,t){FB[apn]=FB[apn]||{};FB[apn].n=t;saveFB();}
function updCount(){const el=document.getElementById('fbcount');if(!el)return;
const n=Object.values(FB).filter(f=>f.v||(f.n&&f.n.trim())).length;
el.textContent=n+' of '+rows.length+' reviewed';}
function exportCSV(){const nm=(document.getElementById('rvname').value||'').trim()||'unnamed';
const recs=Object.entries(FB).filter(([a,f])=>f.v||(f.n&&f.n.trim()));
if(!recs.length){alert('Nothing marked yet — set a verdict (Good fit / Unsure / Not a target) or a note on at least one property first.');return;}
const byId=Object.fromEntries(rows.map(r=>[r.apn,r]));
const q=s=>'"'+String(s==null?'':s).replace(/"/g,'""')+'"';
const lbl={fit:'good fit',maybe:'unsure',no:'not a target'};
let csv='reviewer,apn,address,score,verdict,note\\n';
recs.forEach(([apn,f])=>{const r=byId[apn]||{};
csv+=[q(nm),q(apn),q(r.addr),q(r.score),q(lbl[f.v]||''),q(f.n||'')].join(',')+'\\n';});
const b=new Blob([csv],{type:'text/csv'});const u=URL.createObjectURL(b);
const a=document.createElement('a');a.href=u;a.download='feedback_'+nm.replace(/[^a-z0-9]+/gi,'_')+'.csv';
document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(u);}
const fmt=n=>n==null?'—':n.toLocaleString(undefined,{maximumFractionDigits:0});
function fmtPhone(p){const d=String(p==null?'':p).replace(/\\D/g,'');
return d.length===10?'('+d.slice(0,3)+') '+d.slice(3,6)+'-'+d.slice(6):String(p||'');}
// Compact contact for the table cell: person (truncated) + best phone, else best email.
function contactCell(r){const ph=(r.phones&&r.phones[0])?fmtPhone(r.phones[0]):'',
em=(r.emails&&r.emails[0])?r.emails[0]:'';
if(!ph&&!em&&!r.person)return '<span class="chip none">—</span>';
let h='';if(r.person)h+='<div class="cperson" title="'+esc(r.person)+'">'+esc(r.person)+'</div>';
if(ph)h+='<div class="cph">'+esc(ph)+'</div>';else if(em)h+='<div class="cem" title="'+esc(em)+'">'+esc(em)+'</div>';
return h;}
// Full contact for the detail panel: person + role, every phone (tel:) and email (mailto:).
function contactDetail(r){const hasP=r.phones&&r.phones.length,hasE=r.emails&&r.emails.length;
if(!hasP&&!hasE&&!r.person)return '<span class="muted">— no source-backed contact yet</span>';
let h='';if(r.person)h+='<b>'+esc(r.person)+'</b>'+(r.prole?' <span class="muted">('+esc(String(r.prole).replace(/_/g,' '))+')</span>':'')+(hasP||hasE?'<br>':'');
if(hasP)h+=r.phones.map(p=>'<a href="tel:'+esc(String(p).replace(/\\D/g,''))+'">'+esc(fmtPhone(p))+'</a>').join(' &nbsp;·&nbsp; ');
if(hasP&&hasE)h+='<br>';
if(hasE)h+=r.emails.map(e=>'<a href="mailto:'+esc(e)+'">'+esc(e)+'</a>').join(' &nbsp;·&nbsp; ');
if(r.cc)h+=' <span class="chip '+(r.cc==='high'?'hot':(r.cc==='medium'?'warnc':'soft'))+'" style="margin-left:6px">'+esc(r.cc)+' confidence</span>';
return h;}
const otSel=document.getElementById('otype');
[...new Set(rows.map(r=>r.ot))].sort().forEach(t=>{const o=document.createElement('option');o.value=t;o.textContent=t;otSel.appendChild(o)});
const citySel=document.getElementById('city');
// Columbus-first (founder request): lead with Columbus in the dropdown, and open the
// entry view filtered to Columbus when it actually has universe rows.
const CITIES=[...new Set(rows.map(r=>r.city).filter(Boolean))]
.sort((a,b)=>a==='Columbus'?-1:b==='Columbus'?1:a.localeCompare(b));
CITIES.forEach(c=>{const o=document.createElement('option');o.value=c;o.textContent=c;citySel.appendChild(o)});
if(CITIES.length<2)citySel.style.display='none';  // no point filtering by city when there's only one
const _colb=(DATA.markets||[]).find(m=>m.city==='Columbus');
if(_colb&&_colb.n_universe>0)citySel.value='Columbus';  // default the landing view to Columbus
{const ht=document.getElementById('htitle');
if(ht&&CITIES.length)ht.textContent=(CITIES.length===1?CITIES[0]:CITIES.join(' · '))+' — off-market industrial';}
let sortK='rank',asc=true,open=null;
function chips(r){let h='';h+='<span class="chip'+((r.ot==='trust'||r.ot==='individual')?' hot':'')+'">'+r.ot+'</span>';
if(r.oos)h+='<span class="chip">out-of-state</span>';
if(r.bucket!=='universe')h+='<span class="chip warnc">manual review</span>';
if(r.sfc==='mismatch')h+='<span class="chip redc">SF mismatch</span>';
if(r.obs)h+='<span class="chip">imagery</span>';
if(r.obs&&r.obs.match===false)h+='<span class="chip redc">use mismatch</span>';return h}
function sigsum(r){const v=r.sig.filter(s=>s.type==='code_violation').length,
p=r.sig.filter(s=>s.type==='permit_anomaly').length;let h='';
if(v)h+='<span class="chip redc">'+v+' violation'+(v>1?'s':'')+'</span>';
if(p)h+='<span class="chip soft" title="No recent building permits — weaker signal; the permit feed only goes back ~3 years">no recent permits</span>';
return h||'<span class="chip none">—</span>'}
function compBreak(r){const c=r.comp||{};
if(!Object.keys(c).length)return '<div class="cgrid"><span>Not scored — '+(r.gate||'manual review (60–75k SF)')+'</span></div>';
const LV=liveFor(r);
const live=CKEYS.filter(k=>LV.includes(k)).map(k=>[k,c[k]||0,CMAX[k]]).sort((a,b)=>b[1]-a[1]);
const dormant=CKEYS.filter(k=>!LV.includes(k));
let h='<div class="bkhd">Score breakdown — <b>'+(r.score==null?'—':r.score)+'</b> of '+ceilFor(r)+' reachable in '+(r.city||'this market')+'</div><div class="cbreak">';
live.forEach(([k,v,mx])=>{const pct=mx?Math.round(v/mx*100):0;
h+='<div class="lab">'+(CLABEL[k]||k.replaceAll('_',' '))+'</div>'
+'<div class="track"><i class="fill'+(v>0?'':' z')+'" style="width:'+pct+'%"></i></div>'
+'<div class="val"><b>'+(+v)+'</b> / '+mx+'</div>';});
h+='</div>';
if(dormant.length)h+='<div class="pendrow">Locked until imagery + tax data land: '
+dormant.map(k=>(CLABEL[k]||k.replaceAll('_',' '))+' <b>'+CMAX[k]+'</b>').join(' · ')+'</div>';
return h;}
// The county code-violation feed jams "Type: X Description: Y Additional Comments: Z"
// into one blob, and permit anomalies are prefixed with a machine key. Pull out the
// human-readable part so the evidence reads like a sentence, not a data dump.
function cleanEv(x){const t=String(x.detail||'').trim();
if(x.type==='permit_anomaly')return esc(t.replace(/^[a-z0-9_]+:\\s*/,''));
let typ='',desc=t;const di=t.search(/Description:/i);
if(di>=0){const ti=t.search(/Type:/i);
if(ti>=0&&ti<di)typ=t.slice(ti+5,di).trim().replace(/^Property Violations\\s*-\\s*/i,'').trim();
desc=t.slice(di+12);const ai=desc.search(/Additional Comments:/i);if(ai>=0)desc=desc.slice(0,ai);desc=desc.trim();}
return (typ?'<b>'+esc(typ)+'</b> — ':'')+esc(desc);}
function evidence(r){if(!r.sig.length)return '<div class="muted" style="margin:2px 0 12px">No distress signals on file.</div>';
return '<div class="evhd">Distress evidence</div><div class="evlist">'+r.sig.map(x=>{const v=x.type==='code_violation',vis=x.type==='visual_distress';
const tag=v?'Violation':vis?'Visual':'Permit';
return '<div class="evrow"><span class="tag '+(v||vis?'v':'p')+'">'+tag+'</span>'
+'<div class="ev">'+(x.date?'<span class="when">'+x.date+'</span>':'')+cleanEv(x)+'</div></div>';}).join('')+'</div>';}
// Site assessment from the imagery/VLM pass (site_observations). Mirrors the call sheet's
// "Site assessment" block so a reviewer sees the same read on the dashboard.
function occLabel(p,s){
if(p==='empty'&&s==='no')return 'vacancy signals — empty lot, no signage';
if(p==='empty'||p==='sparse'||s==='no')return 'possible vacancy — sparse / no signage';
if(p==='not_visible'&&s==='not_visible')return 'occupancy unclear from imagery';
if(!p&&!s)return 'not assessed';
return 'clearly active (occupied)';}
function siteAssess(r){const o=r.obs;if(!o)return '';
let h='<div class="evhd">Site assessment <span class="muted">(imagery / VLM)</span></div><dl class="facts">';
h+='<dt>Occupancy</dt><dd>'+esc(occLabel(o.park,o.sign))+' <span class="muted">(parking '+esc(o.park||'—')+', signage '+esc(o.sign||'—')+')</span></dd>';
if(o.use){const fl=o.match===false?' — ⚠️ NO LONGER MATCHES assessor land use':o.match===true?' ✓ matches land use':'';
h+='<dt>Observed use</dt><dd>'+esc(o.use)+(fl?'<b>'+esc(fl)+'</b>':'')+'</dd>';}
if(o.ten&&o.ten.length){const m=[o.tency,o.occ].filter(Boolean).join(' / ');
h+='<dt>Tenant(s)</dt><dd>'+esc(o.ten.join(', '))+(m?' <span class="muted">('+esc(m)+')</span>':'')+'</dd>';}
const phys=[];if(o.docks!=null)phys.push('~'+o.docks+' docks');if(o.drive!=null)phys.push('~'+o.drive+' drive-ins');
if(o.div)phys.push('divisibility '+o.div);if(o.truck)phys.push('truck '+o.truck);if(o.cond)phys.push('condition '+o.cond);
if(phys.length)h+='<dt>Physical</dt><dd>'+esc(phys.join(' · '))+'</dd>';
if(o.ctx)h+='<dt>Context</dt><dd>'+esc(o.ctx)+'</dd>';
if(o.note)h+='<dt>Observed</dt><dd>'+esc(o.note)+'</dd>';
h+='</dl>';
if(o.src)h+='<div class="muted" style="margin:-6px 0 12px">source: <a target="_blank" rel="noopener" href="'+o.src+'">satellite imagery ↗</a>'+(o.cap?' · '+esc(o.cap):'')+(o.ver?' · '+esc(o.ver):'')+'</div>';
return h;}
// Last sale price + $/SF. A bulk/portfolio sale (same date+price on >1 parcel, flagged via r.pn)
// — or any absurd >$1,000/SF — shows the total but suppresses the per-SF, since dividing a
// whole-deal price by one parcel's SF is meaningless.
function salePrice(r){if(!r.sale)return '—';
if(!r.price)return '$0 <span class="muted">($0 / non-arm\\'s-length recorded)</span>';
const psf=r.sf?r.price/r.sf:0,bulk=r.pn>1||psf>1000;
if(bulk)return '$'+fmt(r.price)+' <span class="muted">· '+(r.pn>1?r.pn+'-parcel bulk sale':'bulk/portfolio?')+' — per-SF n/a</span>';
return '$'+fmt(r.price)+(psf?' <span class="muted">· $'+psf.toFixed(2)+'/SF</span>':'');}
function facts(r){const F=[['Owner','<b>'+esc(r.own)+'</b>'],['Contact',contactDetail(r)],
['Mailing',r.mail?esc(r.mail):'—'],
['Land use',esc(r.lu||'—')],
['Building',fmt(r.sf)+' SF total'+(r.sfL&&r.sfL!==r.sf?' · largest '+fmt(r.sfL)+' SF':'')+(r.nb?' · '+r.nb+' building'+(r.nb>1?'s':''):'')],
['Clear height',r.ch!=null?('~'+r.ch.toFixed(0)+' ft <span class="muted">· '+(r.chs||'est')+' roof est — interior clear ~2-4 ft less; confirm on call</span>'):'<span class="muted">— no LiDAR estimate</span>'],
// av<=1 = not in the county feed (Charlotte's assessed_value is absent) — show "—", not a fake $0/SF.
['Assessed',r.av>1?('$'+fmt(r.av)+(r.sf?' <span class="muted">· $'+(r.av/r.sf).toFixed(2)+'/SF</span>':'')):'<span class="muted">— not in county feed</span>'],
['Last sale',r.sale||'—'],['Sale price',salePrice(r)]];
return '<dl class="facts">'+F.map(kv=>'<dt>'+kv[0]+'</dt><dd>'+kv[1]+'</dd>').join('')+'</dl>';}
function detail(r){const mapq=encodeURIComponent(r.addr+', '+(r.place||r.city||''));
let rv='';
if(REVIEW){const f=FB[r.apn]||{};const on=v=>f.v===v?' on':'';
rv='<div class="vbtns">'
+'<button class="vb good'+on('fit')+'" data-v="fit" data-apn="'+r.apn+'">Good fit</button>'
+'<button class="vb maybe'+on('maybe')+'" data-v="maybe" data-apn="'+r.apn+'">Unsure</button>'
+'<button class="vb bad'+on('no')+'" data-v="no" data-apn="'+r.apn+'">Not a target</button>'
+'</div><textarea class="rnote" data-apn="'+r.apn+'" placeholder="Notes: already sold, owner-occupied national tenant, not really a warehouse, wrong submarket...">'+esc(f.n)+'</textarea>';}
return '<tr class="det"><td colspan="12">'
+compBreak(r)
+facts(r)
+siteAssess(r)
+evidence(r)
+'<a class="mapbtn" target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query='+mapq+'">Open in Google Maps ↗</a>'
+rv+'</td></tr>'}
function render(){const q=document.getElementById('q').value.toLowerCase(),
ot=otSel.value,cy=citySel.value,minsf=+document.getElementById('minsf').value,
maxsf=+document.getElementById('maxsf').value,
minscore=document.getElementById('minscore').value,
maxch=+document.getElementById('maxch').value,
maxmi=+document.getElementById('maxmi').value,minhold=+document.getElementById('minhold').value,
ownerloc=document.getElementById('ownerloc').value,
mr=document.getElementById('mr').checked,so=document.getElementById('sigonly').checked;
// score filter is tier-based (matches the visible colour pills): 'hi' = strong only,
// 'mid' = strong or moderate. tier(null)==='na' so unscored rows drop out when a min is set.
let f=rows.filter(r=>(mr||r.bucket==='universe')&&r.sf>=minsf&&(!maxsf||r.sf<=maxsf)
&&(!minscore||(minscore==='hi'?tier(r)==='hi':(tier(r)==='hi'||tier(r)==='mid')))
&&(!maxch||r.ch==null||r.ch<=maxch)
&&(!maxmi||r.mi<=maxmi)&&(!minhold||r.hold>=minhold)
&&(!ownerloc||(ownerloc==='out'?r.oos:!r.oos))&&(!ot||r.ot===ot)&&(!cy||r.city===cy)
&&(!so||r.sig.length)&&(!q||(r.addr+' '+r.own+' '+r.apn+' '+(r.person||'')+' '+(r.phones||[]).join(' ')+' '+(r.emails||[]).join(' ')).toLowerCase().includes(q)));
f.sort((a,b)=>{let x=a[sortK],y=b[sortK];if(x==null)x=-1;if(y==null)y=-1;
if(typeof x==='string')return asc?x.localeCompare(y):y.localeCompare(x);return asc?x-y:y-x});
document.getElementById('stats').innerHTML=
'<span><b>'+f.length+'</b> showing</span><span><b>'+DATA.n_universe+'</b> in universe</span>'
+'<span><b>'+DATA.n_manual+'</b> manual review</span>'
+((DATA.markets&&DATA.markets.length>1)?'<span>'+DATA.markets.map(m=>'<b>'+m.n_universe+'</b> '+m.city).join(' · ')+'</span>':'')
+'<span><b>'+DATA.generated+'</b> data as of</span>';
tb.innerHTML=f.map(r=>'<tr class="main" data-apn="'+r.apn+'">'
+'<td>'+(r.score==null?'—':r.rank)+'</td>'
+'<td><div class="addr">'+((REVIEW&&FB[r.apn]&&FB[r.apn].v)?VICON[FB[r.apn].v]:'')+r.addr+'</div><div class="apn">'+r.apn+' &nbsp;'+chips(r)+'</div></td>'
+'<td>'+(r.city||'—')+'</td>'
+'<td class="r">'+fmt(r.sf)+'</td><td class="r">'+(r.nb||'—')+'</td>'
+'<td class="r">'+(r.yr||'—')+'</td>'
+'<td class="r">'+(r.ch!=null?r.ch.toFixed(0):'<span class="muted">—</span>')+'</td>'
+'<td class="r">'+r.mi.toFixed(1)+'</td>'
+'<td class="r">'+r.hold.toFixed(0)+'y</td>'
+'<td><div class="scwrap"><span class="scorepill '+tier(r)+'">'+(r.score==null?'—':r.score)+'</span>'
+(r.score!=null?'<span class="sbar '+tier(r)+'"><i style="width:'+Math.min(100,Math.round(r.score/ceilFor(r)*100))+'%"></i></span><span class="fitpct">'+Math.round(r.score/ceilFor(r)*100)+'% fit</span>':'')+'</div></td>'
+'<td>'+sigsum(r)+'</td>'
+'<td>'+contactCell(r)+'</td></tr>'+(open===r.apn?detail(r):'')).join('')}
tb.addEventListener('click',e=>{
const vb=e.target.closest('.vb');if(vb){setVerdict(vb.dataset.apn,vb.dataset.v);return;}
if(e.target.closest('.rnote'))return;
const tr=e.target.closest('tr.main');if(!tr)return;
if(e.target.closest('a'))return;open=open===tr.dataset.apn?null:tr.dataset.apn;render()});
tb.addEventListener('input',e=>{if(e.target.classList.contains('rnote'))setNote(e.target.dataset.apn,e.target.value);});
document.querySelectorAll('th[data-k]').forEach(h=>h.addEventListener('click',()=>{
const k=h.dataset.k;if(sortK===k)asc=!asc;else{sortK=k;asc=(k==='rank'||k==='addr')}render()}));
['q','city','otype','minsf','maxsf','minscore','maxch','maxmi','minhold','ownerloc','mr','sigonly']
.forEach(id=>document.getElementById(id).addEventListener('input',render));
render();updCount();
// The clear-height filter must NEVER open pre-applied: browsers restore form-control values on
// back/forward (bfcache) and session-restore, so returning from the Map view could otherwise
// reopen the table still filtered to a previously-picked '≤ N ft'. pageshow fires on the initial
// load AND on bfcache restore — force it back to "Any clear height" (no clear-height filter) each time.
window.addEventListener('pageshow',function(){var m=document.getElementById('maxch');
if(m&&m.value!=='0'){m.value='0';render();}});
</script></body></html>
"""


REVIEW_BANNER = """<div class="rvb">
<h3>Quick gut-check, please — this is a first-pass machine ranking</h3>
This is an automated rank of every off-market industrial property (75k+ SF) across our
target markets that could fit our cowarehousing buy box. Scores are provisional: vacancy and
condition aren't in yet (that's the Street View / aerial AI pass), so for now rank is
driven mostly by location, age, hold time and code violations. I want your eyes on it:
<ol>
<li><b>Is each one actually a target?</b> Open a row, hit "Open in Google Maps", and mark
<b>Good fit / Unsure / Not a target</b>. Flag anything obviously off — already sold,
owner-occupied by a national tenant, not really a warehouse, or the wrong submarket.</li>
<li><b>What's missing?</b> If you know a great off-market building that <i>isn't</i> here, note it.</li>
<li><b>Does the ranking feel right?</b> Anything ranked too high or too low?</li>
</ol>
Add a note on anything you flag, then click <b>Download my feedback</b> and email me the
CSV. Your marks save in this browser as you go, so you can stop and come back.</div>
<div class="exbar">
<input id="rvname" placeholder="Your name" style="width:150px">
<button class="btn primary" onclick="exportCSV()">Download my feedback</button>
<span class="cnt" id="fbcount"></span>
</div>"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=None)
    ap.add_argument("--review", action="store_true",
                    help="build the shareable review copy (feedback controls + framing)")
    ap.add_argument("--from-json", default=None, metavar="PATH",
                    help="build from a saved JSON data snapshot instead of the DB — "
                         "regenerate the HTML on a machine with no Postgres")
    ap.add_argument("--dump-json", default=None, metavar="PATH",
                    help="also write the collected DB data to this JSON path — a reusable, "
                         "DB-free snapshot you can later rebuild from with --from-json")
    args = ap.parse_args()
    out = Path(args.out) if args.out else Path(
        "exports/dashboard_review.html" if args.review else "exports/dashboard.html")

    if args.from_json:
        data = json.loads(Path(args.from_json).read_text(encoding="utf-8"))
        data.setdefault("comp_max", _comp_max())  # backfill snapshots saved before the breakdown bars existed
        data.setdefault("markets", [])             # backfill pre-multi-market snapshots
        data.setdefault("city_ceil", {})           # backfill pre-A1 snapshots (client falls back to a global ceiling)
        data.setdefault("city_live", {})
    else:
        data = collect()
        if args.dump_json:
            Path(args.dump_json).parent.mkdir(parents=True, exist_ok=True)
            Path(args.dump_json).write_text(
                json.dumps(data, default=_js), encoding="utf-8")
            print(f"data snapshot: {args.dump_json} written "
                  f"({len(data['rows'])} rows, no DB needed to rebuild)")

    payload = json.dumps(data, default=_js).replace("</", "<\\/")
    html = (TEMPLATE
            .replace("__DATA__", payload)
            .replace("__GEN__", data["generated"])
            .replace("__REVIEW__", REVIEW_BANNER if args.review else "")
            .replace("__REVIEW_FLAG__", "true" if args.review else "false"))
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    mode = "review copy" if args.review else "dashboard"
    print(f"{mode}: {out} written — {data['n_universe']} universe + "
          f"{data['n_manual']} manual-review rows ({out.stat().st_size//1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
